version: "3.7"

services:
  endpoint:
    build:
      context: ./endpoint
    image: stream-backend-endpoint
    ports:
      - "1935:1935"
  pull_relay:
    build:
      context: ./pull_relay
    environment:
      PULL_ENDPOINT: "rtmp://endpoint/live/test"
    image: stream-backend-pull-relay
    ports:
      - "8080:80"
      - "1936:1935"
  push_relay:
    build:
      context: ./push_relay
    env_file: .env
    image: stream-backend-push-relay