version: "3.7"

services:
  client:
    build:
      context: ./client
    environment:
      __STREAM_URL__: "http://pull_relay/hls/source/index.m3u8"
    image: stream-backend-client
    ports:
      - "8080:8080"
  endpoint:
    build:
      context: ./endpoint
    image: stream-backend-endpoint
    ports:
      - "1935:1935"
  pull_relay:
    build:
      context: ./pull_relay
    environment:
      PULL_ENDPOINT: "rtmp://endpoint/live/test"
    image: stream-backend-pull-relay
    ports:
      - "8081:80"
      - "1936:1935"
  push_relay:
    build:
      context: ./push_relay
    env_file: .env
    image: stream-backend-push-relay